name: DevSecOps Pipeline
on: [push] # Chạy tự động khi có code mới đẩy lên

jobs:
  Secret-Scanning:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Clone mã nguồn về máy quét
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 2. Quét mật khẩu bị lộ bằng Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
   
   Container-Scanning:
     runs-on: ubuntu-latest
     steps:
       - name: 1. Clone ma nguon
         uses: actions/checkout@v3

       - name: 2. Dong goi Docker Image
         run: docker build -t my-app:latest .

       - name: 3. Quet lo hong Container bang Trivy
         uses: aquasecurity/trivy-action@master
         with:
           image-ref: 'my-app:latest'
           format: 'table'
           exit-code: '1' # Bắt buộc dừng (Báo lỗi đỏ) nếu có lỗi nguy hiểm
           severity: 'CRITICAL,HIGH'
